
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INITIALleftPLUSMINUSleftTIMESDIVIDERESTleftLPARENRPARENAND BREAK CHAR COLON COMENTLINE COMENTMULTYLINE COMMA CONDITIONAL_ELSE CONDITIONAL_IF CONTINUE DATA_BOOL DIFFERENT DIVIDE DOT_AN_DCOMMA FLOAT GREATER ID INT IQUAL IQUALS IQUAL_GREATER IQUAL_LESS ITERATIVE_DO ITERATIVE_WHILE LESS LKEY LPAREN METHOD_RETURN METHOD_VOID MINUS NOT OR PLUS REST RKEY RPAREN STRING TIMES TYPE_BOOL TYPE_CHAR TYPE_DOUBLE TYPE_INT TYPE_STRING\n        INITIAL : L_INST \n        \n        L_INST : L_INST INTS\n               | INTS\n        \n        INTS : METHOD_VOID ID LPAREN RPAREN LKEY RKEY \n             | METHOD_VOID ID LPAREN L_PARAMS RPAREN LKEY RKEY\n        \n        L_PARAMS : L_PARAMS COMMA PARAM\n                 | PARAM\n        \n        PARAM : TYPE_INT ID\n              | TYPE_STRING ID\n        '
    
_lr_action_items = {'METHOD_VOID':([0,2,3,5,18,21,],[4,4,-3,-2,-4,-5,]),'$end':([1,2,3,5,18,21,],[0,-1,-3,-2,-4,-5,]),'ID':([4,11,12,],[6,16,17,]),'LPAREN':([6,],[7,]),'RPAREN':([7,9,10,16,17,20,],[8,14,-7,-8,-9,-6,]),'TYPE_INT':([7,15,],[11,11,]),'TYPE_STRING':([7,15,],[12,12,]),'LKEY':([8,14,],[13,19,]),'COMMA':([9,10,16,17,20,],[15,-7,-8,-9,-6,]),'RKEY':([13,19,],[18,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'INITIAL':([0,],[1,]),'L_INST':([0,],[2,]),'INTS':([0,2,],[3,5,]),'L_PARAMS':([7,],[9,]),'PARAM':([7,15,],[10,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> INITIAL","S'",1,None,None,None),
  ('INITIAL -> L_INST','INITIAL',1,'p_INITIAL','Lexico.py',223),
  ('L_INST -> L_INST INTS','L_INST',2,'p_L_INST','Lexico.py',229),
  ('L_INST -> INTS','L_INST',1,'p_L_INST','Lexico.py',230),
  ('INTS -> METHOD_VOID ID LPAREN RPAREN LKEY RKEY','INTS',6,'p_INTS','Lexico.py',240),
  ('INTS -> METHOD_VOID ID LPAREN L_PARAMS RPAREN LKEY RKEY','INTS',7,'p_INTS','Lexico.py',241),
  ('L_PARAMS -> L_PARAMS COMMA PARAM','L_PARAMS',3,'p_L_PARAMS','Lexico.py',252),
  ('L_PARAMS -> PARAM','L_PARAMS',1,'p_L_PARAMS','Lexico.py',253),
  ('PARAM -> TYPE_INT ID','PARAM',2,'p_PARAM','Lexico.py',264),
  ('PARAM -> TYPE_STRING ID','PARAM',2,'p_PARAM','Lexico.py',265),
]
